-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "combo2Price" INTEGER NOT NULL DEFAULT 165000,
ADD COLUMN     "combo3Price" INTEGER NOT NULL DEFAULT 240000,
ADD COLUMN     "freeDeliveryAt" INTEGER NOT NULL DEFAULT 3;
